title = "__φ(◎◎ヘ) Fadhlika"

theme = "zola-bearblog"

# The URL the site will be built for
base_url = "https://fadhlika.com"

ignored_content = ["*.tldr"]

generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

default_language = "en"

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"

[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "Projects"
url = "@/projects.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"
